name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for GitVersioning
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/Coderynx.MediatorKit.Abstractions/Coderynx.MediatorKit.Abstractions.csproj
      
    - name: Restore dependencies
      run: dotnet restore src/Coderynx.MediatorKit/Coderynx.MediatorKit.csproj
      
    - name: Restore test dependencies
      run: dotnet restore tests/Coderynx.CqrsKit.Tests/Coderynx.CqrsKit.Tests.csproj
      
    - name: Build
      run: |
        dotnet build src/Coderynx.MediatorKit.Abstractions/Coderynx.MediatorKit.Abstractions.csproj --configuration Release --no-restore
        dotnet build src/Coderynx.MediatorKit/Coderynx.MediatorKit.csproj --configuration Release --no-restore
        
    - name: Test
      run: dotnet test tests/Coderynx.CqrsKit.Tests/Coderynx.CqrsKit.Tests.csproj --configuration Release --no-build --verbosity normal
      
    - name: Get version
      id: version
      run: |
        dotnet tool install --global nbgv
        echo "version=$(nbgv get-version -v NuGetPackageVersion)" >> $GITHUB_OUTPUT
        echo "semver=$(nbgv get-version -v SemVer2)" >> $GITHUB_OUTPUT
        
    - name: Pack
      run: |
        dotnet pack src/Coderynx.MediatorKit.Abstractions/Coderynx.MediatorKit.Abstractions.csproj --configuration Release --no-build --output ./nupkg
        dotnet pack src/Coderynx.MediatorKit/Coderynx.MediatorKit.csproj --configuration Release --no-build --output ./nupkg
        
    - name: Upload packages as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages-${{ steps.version.outputs.version }}
        path: ./nupkg/*.nupkg
        
    - name: Upload symbols as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-symbols-${{ steps.version.outputs.version }}
        path: ./nupkg/*.snupkg
